'use strict';

const websiteText = {

  // 简体中文
  'zhCN': {
    SIGN_IN: '登入',
    SIGN_OUT: '登出',
    SEARCH: '搜索',
    MATCH: '匹配',
    PROJECT_MANAGEMENT: '项目管理',
    JOB_DESCRIPTION_MANAGEMENT: '职位管理',
    OPEN_JOB_DESCRIPTION: '已开放职位',
    CUSTOMER_MANAGEMENT: '客户管理',
    OWN_CUSTOMER_MANAGEMENT: '已拥有客户',
    DEVELOPMENT_CUSTOMER_MANAGEMENT: '待开发客户',
    PROFILE: '个人中心',
    DELETE: '删除',
    VIEW_DETAILS: '查看详情',
    DETAILS_INFORMATION: '详细信息',
    CREATION: '新建',
    COMPANY_NAME: '公司名称',
    TELLPHONE: '座机',
    MOBILEPHONE: '手机',
    CONTACT: '联系人',
    CONTACT_WAY: '联系方式',
    EMAIL: '邮箱',
    OPEN_POSITION: '开放职位',
    POSITION: '职位',
    NEW_VISITING_SITUATION: '最新陌拜情况',
    VISITING_SITUATION: '陌拜情况',
    VISITING_INFORMATION: '陌拜信息',
    DATE: '日期',
    VISITOR: '陌拜人',
    PRODUCT: '产品',
    ADDRESS: '地址',
    WEBSITE: '网站',
    COMPANY_INTRODUCTION: '公司概述',
    DISTRICT: '区域',
    RELATED_COMPANY: '相关公司',
    OPERATION: '操作',
    SUBMIT: '提交',
    EXTENDED_INFORMATION: '扩展信息',
    BASIC_INFORMATION: '基本信息',
    INPUT_PLACEHOLDER: '请输入',
    EMAIL_VALIDATE_TIP: '请输入正确的邮箱地址',
    RESET: '重置',
    CANCEL: '取消',
    EDIT: '编辑',
    SAVE: '保存',
    ADD: '添加',
    CREATOR: '提交人',
    CURRENT_STATUS: '当前状态',
    MATCH_ACTION: '进行匹配',
    JOB_DESCRIPTION_ID: 'ID',
    JOB_DESCRIPTION_NAME: '职位名称',
    JOB_DESCRIPTION_CONTENT: '职位描述内容',
    'OPENING': '开放',
    'CLOSED': '关闭',
    EDIT_JOB_DESCRIPTION: '编辑职位描述',
    JOB_DESCRIPTION_CREATION: '创建职位',
    ALL: '所有',
    NOT_NULL: '不为空',
    COMPANY_NAME_VALIDATE_MSG: '请输入公司名称',
    JOB_DESCRIPTION_NAME_VALIDATE_MSG: '请输入职位名称',
    JOB_DESCRIPTION_CONTENT_VALIDATE_MSG: '请输入职位描述内容'
  },

  // 待扩展语言
};

module.exports = websiteText;
