'use strict';

const websiteText = {

  // 简体中文
  'zhCN': {
    SIGN_IN: '登入',
    SIGN_OUT: '登出',
    SIGN_OUT_CONFIRM_MSG: '是否确定登出?',

    NAME:'姓名',
    EMAIL: '邮箱',
    GENDER: '性别',
    PHONE: '手机',
    AGE: '年龄',
    EDUCATION: '学历',
    MARITAL_STATUS: '婚姻状况',
    SCHOOL: '学校',
    POSITION: '职位',
    COMPANY:  '公司',
    EXPERIENCE: '工作经历',
    EDUCATION_HISTORY: '教育经历',
    CLASSIFY: '行业',

    YES: '是',
    NO: '否',

    PROFILE: '个人中心',
    NOTICE: '消息',
    MANGEMENT: '管理',
    SEARCH: '简历搜索',
    JOBSEARCH: '职位匹配',
    MATCH: '匹配',
    PROJECT_SEARCH: '项目查询',
    RESUME_UPLOADER: '简历上传',
    PRO_RESUME_UPLOADER: '个人简历',
    VIP_MANAGEMENT: '会员服务',
    BECOME_MEMBER: '成为会员',
    BEST_EXCELLENT: '每日优秀',

    SUCCESS: '成功',
    FAIL: '失败',
    ACTION_SUCCESS: '操作成功！',
    ACTION_FAIL: '操作失败！',

    ADMIN_MANAGEMENT: '权限管理',
    MEMBER_MANAGEMENT: '成员管理',
    PROJECT_MANAGEMENT: '项目管理',
    CUSTOMER_MANAGEMENT: '客户管理',

    JOB_DESCRIPTION_MANAGEMENT: '职位管理',
    OPEN_JOB_DESCRIPTION: '已开放职位',
    CUSTOMER_MANAGEMENT: '客户管理',
    OWN_CUSTOMER_MANAGEMENT: '已签约客户',
    DEVELOPMENT_CUSTOMER_MANAGEMENT: '待开发客户',
    
    COMPANY_NAME: '公司名称',
    COMPANY_INTRODUCTION: '公司概述',
    PRODUCT: '产品',
    TELLPHONE: '座机',
    ADDRESS: '地址',
    WEBSITE: '网站',
    DISTRICT: '区域',
    CONTACT: '联系人',
    CONTACT_WAY: '联系方式',
    MOBILEPHONE: '手机',
    EMAIL: '邮箱',
    OPEN_POSITION: '开放职位',
    NEW_VISITING_SITUATION: '最新陌拜情况',
    POSITION: '职位',
    RESPONSIBLE: '跟进人',
    PRIORITY: '优先级',
    REMINDER: '待联系',
    QUIT_MEMBER: '退出公司',

    VISITING_SITUATION: '陌拜情况',
    VISITING_INFORMATION: '陌拜信息',
    DATE: '日期',
    VISITOR: '陌拜人',

    
    VIEW_DETAILS: '查看详情',
    DETAILS_INFORMATION: '详细信息',
    EXTENDED_INFORMATION: '扩展信息',
    BASIC_INFORMATION: '基本信息',
    RELATED_COMPANY: '相关公司',
    
    OPERATION: '操作',
    CREATION: '新建',
    DELETE: '删除',
    SUBMIT: '提交',
    RESET: '重置',
    CANCEL: '取消',
    EDIT: '编辑',
    SAVE: '保存',
    ADD: '添加',
    MATCH_ACTION: '进行匹配',
    UPLOAD: '上传',
    ACCEPT: '接受',
    REJECT: '拒绝',
    ELEVATE: '授予管理员权限',
    REVOKE: '撤销管理员权限',

    ELEVATE_SUCCESS: '授予权限成功！',
    ELEVATE_FAIL: '授予权限失败！',
    REVOKE_SUCCESS: '撤销权限成功！',
    REVOKE_FAIL: '撤销权限失败！',

    JOB_DESCRIPTION_ID: 'ID',
    JOB_DESCRIPTION_NAME: '职位名称',
    JOB_DESCRIPTION_CONTENT: '职位描述内容',
    REMARKS: '备注',
    COMMENTARY: '关键字',
    APPEND_COMMENTARY: '使用关键字',
    CURRENT_STATUS: '当前状态',
    ALL: '所有',
    OPENING: '开放',
    CLOSED: '关闭',
    CREATOR: '提交人',
    EDIT_JOB_DESCRIPTION: '编辑职位描述',
    JOB_DESCRIPTION_CREATION: '创建职位',

    NOT_NULL: '不为空',
    INPUT_PLACEHOLDER: '请输入',
    EMAIL_VALIDATE_TIP: '请输入正确的邮箱地址',
    COMPANY_NAME_VALIDATE_MSG: '请输入公司名称',
    JOB_DESCRIPTION_NAME_VALIDATE_MSG: '请输入职位名称',
    JOB_DESCRIPTION_CONTENT_VALIDATE_MSG: '请输入职位描述内容',

    SENT_SUCCESS_MSG: '发送成功',
    SENT_FAIL_MSG: '发送失败',

    SAVE_SUCCESS_MSG: '已保存!',
    SAVE_FAIL_MSG: '保存失败!',
    ADD_CONFIRM_MSG: '确定要添加这个条目吗?',
    ADD_SUCCESS_MSG: '添加成功!',
    ADD_FAIL_MSG: '添加失败!',
    ADD_NULL_MSG: '项目名不能为空!',
    DELETE_CONFIRM_MSG: '确定要删除这个条目吗?',
    DELETE_SUCCESS_MSG: '删除成功!',
    DELETE_FAIL_MSG: '删除失败!',

    NEW_CREATION: '新增',
    CHANGE: '变更',
    CONFIRM_UOLOAD: '确认上传',
    UPLOAD_SUCCESS_MSG: '上传成功',
    CONFIRM_UPLOAD: '检测到已有个人简历，确认上传更新？',
    UPLOAD_SUCCESS: '简历存入数据库和项目中',
    UPLOAD_EXISTED_PROJECTS: '其他项目中已有该简历',
    UPLOAD_EXISTED_PROJECT: '本项目中已有该简历',
    UPLOAD_NO_CONTACT: '简历中联系方式为空',

    FOLD_MSG: '收起所有信息',
    UNFOLD_MSG: '展开所有信息',

    UNREAD_MESSAGE: '未读',
    READ_MESSAGE: '已读',
    SENT_MESSAGE: '已发',
    INVITED_MESSAGE: '被邀请',
    INVITER_MESSAGE: '已发邀请',
    PROCESSED_MESSAGE: '已处理邀请',
    ACCEPT_INVITE_SUCCESS_MSG: '接受邀请成功！',
    ACCEPT_INVITE_FAIL_MSG: '接受邀请失败！',
    SUCESS_MSG: '成功',
    FAIL_MSG: '失败',

    BROWSING_HISTORY: '浏览历史',
    BOOKMARK: '书签',
    SETTING: '设置',
    MANAGE_INFO: '信息管理',

    RESET_PWD_SUCCESS_MSG: '重置密码成功',
    RESET_PWD_FAIL_MSG: '重置密码失败'
  },

  // 待扩展语言
};

module.exports = websiteText;
